/*
 * This file is generated by jOOQ.
 */
package org.example.jooq;


import org.example.jooq.tables.Author;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;
}
