name: Deploy main to Fly
on:
  push:
    branches: [ main ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu'
            java-version: '21'

      - name: Build JAR
        run: ./gradlew clean bootJar

      - name: Build Docker image
        run: docker build -t my-app-image .

      - name: Deploy to Fly
        run: flyctl deploy --image my-app-image