// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLD4bTQuNzTmraZnPOtlqVhsPW2GkQDWs',
    appId: '1:265255607081:web:1c1b1fa0679627e36db538',
    messagingSenderId: '265255607081',
    projectId: 'hyper-garage-sale-4dfdf',
    authDomain: 'hyper-garage-sale-4dfdf.firebaseapp.com',
    storageBucket: 'hyper-garage-sale-4dfdf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBB9xaZJo5MXRkZ0OeMGuIUZIKLtnCnho',
    appId: '1:265255607081:android:59a828e2989872c46db538',
    messagingSenderId: '265255607081',
    projectId: 'hyper-garage-sale-4dfdf',
    storageBucket: 'hyper-garage-sale-4dfdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFxETCo65n-7HM_hVyEYt1_Ikjdz3RL9o',
    appId: '1:265255607081:ios:106824c2fc9ec6df6db538',
    messagingSenderId: '265255607081',
    projectId: 'hyper-garage-sale-4dfdf',
    storageBucket: 'hyper-garage-sale-4dfdf.firebasestorage.app',
    iosBundleId: 'com.example.hyperGarageSale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFxETCo65n-7HM_hVyEYt1_Ikjdz3RL9o',
    appId: '1:265255607081:ios:106824c2fc9ec6df6db538',
    messagingSenderId: '265255607081',
    projectId: 'hyper-garage-sale-4dfdf',
    storageBucket: 'hyper-garage-sale-4dfdf.firebasestorage.app',
    iosBundleId: 'com.example.hyperGarageSale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLD4bTQuNzTmraZnPOtlqVhsPW2GkQDWs',
    appId: '1:265255607081:web:dcffa78959cb64b96db538',
    messagingSenderId: '265255607081',
    projectId: 'hyper-garage-sale-4dfdf',
    authDomain: 'hyper-garage-sale-4dfdf.firebaseapp.com',
    storageBucket: 'hyper-garage-sale-4dfdf.firebasestorage.app',
  );
}
